auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    endpoint: "s3.ca-central-1.wasabisys.com"
    region: "ca-central-1"
    bucketnames: "akatsuki.pw"
    access_key_id: "${WASABI_ACCESS_KEY}"
    secret_access_key: "${WASABI_SECRET_KEY}"
    s3forcepathstyle: true

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

limits_config:
  max_query_length: 0
  retention_period: 0

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: false
