apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:10905
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: true

  - name: MySQL
    type: mysql
    access: proxy
    url: 127.0.0.1:3306
    database: akatsuki
    user: grafana_ro
    editable: true
    jsonData:
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: grafana-readonly-2026

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://127.0.0.1:6379
    editable: true
